### ISSUE TITLE
Getting a ERROR while running the script

### ISSUE THREAD

**Issue by Drahrekot** [AB-Law/Apple-Discord-Rich-Presence#6]
Its just showing an error when I try to run the python script.

**I ran this command:**
`$python3 discord-apple_music.py`

**and ended up with this error:**
`Traceback (most recent call last):
  File "/Users/drahrekot/Apple-Discord-Rich-Presence/discord-apple_music.py", line 85, in <module>
    RPC.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pypresence/presence.py", line 41, in connect
    self.loop.run_until_complete(self.handshake())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pypresence/baseclient.py", line 121, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
TypeError: _UnixSelectorEventLoop.create_unix_connection() got an unexpected keyword argument 'loop'`

**Desktop**
 - OS: Mac OS 11.6.8 
 - Browser: Safari
 - Version 11.6.8

Please help me out with this. 😊

**Comment by codecracker007** [comment]
update or install ur aiohttp module might be the solution not sure tho
